version: '3.0'

services:
  recap_dev_express_mysql:
    container_name: recap_dev_express_mysql
    image: mysql:5.7.31
    volumes:
      - db_data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: 'recap-dev-test-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "8001:3306"
    restart: unless-stopped

  recap_dev_express_postgres:
    container_name: recap_dev_express_postgres
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8002:5432"
    restart: unless-stopped

  recap_dev_express_mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"


volumes:
  db_data: {}
  postgres:
