name: check-commit

on:
  push:

jobs:
  check-commit:

    runs-on: ubuntu-latest

    services:
      recap_dev_express_mysql:
        image: mysql:5.7.31
        env:
          MYSQL_DATABASE: 'recap-dev-test-db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - "8001:3306"

      recap_dev_express_postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'password'
        ports:
          - "8002:5432"

      recap_dev_express_mongo:
        image: mongo
        ports:
          - "27017:27017"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: tsc
        run: yarn tsc
      - name: build
        run: yarn build:prod
      - name: start server
        run: node dist/index.js &
        env:
          RECAP_DEV_SYNC_ENDPOINT: ${{ secrets.RECAP_DEV_SYNC_ENDPOINT }}
          RECAP_DEV_APP_NAME: 'dev-express-example-project'
      - name: run tests
        run: yarn test
